# Generated by Django 2.2 on 2020-07-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.CharField(default='mcq', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('mcq', models.ManyToManyField(blank=True, null=True, to='core.MCQ')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SubCategory')),
            ],
        ),
    ]
