# Generated by Django 2.2 on 2020-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200716_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='mcq',
            options={'verbose_name_plural': 'MCQs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'NEWS'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name_plural': 'PDFs'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='teamform',
            options={'verbose_name_plural': 'Team Form'},
        ),
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AddField(
            model_name='mcq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='preview_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='preview_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
