# Generated by Django 2.2 on 2020-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200424_0022'),
        ('core', '0004_auto_20200722_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='tests',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
    ]
