# Generated by Django 3.0.8 on 2020-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200909_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
