# Generated by Django 3.0.8 on 2020-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generalnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalnotification',
            options={'verbose_name_plural': 'General Notification'},
        ),
        migrations.AddField(
            model_name='generalnotification',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
