# Generated by Django 2.2 on 2020-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnotification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
