# Generated by Django 2.2 on 2020-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200929_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnotification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
