# Generated by Django 2.2 on 2020-10-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201005_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalnotification',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
