# Generated by Django 2.2 on 2020-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='timeStarted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
