# Generated by Django 3.0.8 on 2020-09-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200923_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
