# Generated by Django 2.2 on 2020-09-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200925_2059'),
        ('quiz', '0007_auto_20200922_0515'),
    ]

    operations = [
    ]
