# Generated by Django 2.2 on 2020-09-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiztaker_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
