# Generated by Django 2.2 on 2020-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200930_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rollout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
