# Generated by Django 2.2 on 2020-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_rollout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answerkey',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
