# Generated by Django 2.2 on 2020-06-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200220_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='courtesy_url',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
