# Generated by Django 2.2 on 2020-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_courtesy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='courtesy_title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
