# Generated by Django 2.2 on 2020-07-31 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_auto_20200424_0022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20200722_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('mcqs', models.ManyToManyField(blank=True, to='core.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='core.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='core.Session')),
                ('summaries', models.ManyToManyField(blank=True, to='core.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='quiz.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='SaveForLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs', models.ManyToManyField(blank=True, to='core.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='core.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='core.Session')),
                ('summaries', models.ManyToManyField(blank=True, to='core.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='quiz.Quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved For Later',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs', models.ManyToManyField(blank=True, to='core.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='core.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='core.Session')),
                ('summaries', models.ManyToManyField(blank=True, to='core.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='quiz.Quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
            },
        ),
    ]
