# Generated by Django 3.1.2 on 2021-03-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='mcqs',
            field=models.ManyToManyField(blank=True, to='core.MCQ'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.payment'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='pdfs',
            field=models.ManyToManyField(blank=True, to='core.PDF'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.promocode'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='core.Session'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='summaries',
            field=models.ManyToManyField(blank=True, to='core.Summary'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='tests',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='mcqs',
            field=models.ManyToManyField(blank=True, to='core.MCQ'),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='pdfs',
            field=models.ManyToManyField(blank=True, to='core.PDF'),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='core.Session'),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='summaries',
            field=models.ManyToManyField(blank=True, to='core.Summary'),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='tests',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='saveforlater',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='mcqs',
            field=models.ManyToManyField(blank=True, to='core.MCQ'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='pdfs',
            field=models.ManyToManyField(blank=True, to='core.PDF'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='core.Session'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='summaries',
            field=models.ManyToManyField(blank=True, to='core.Summary'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tests',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
