# Generated by Django 2.2 on 2020-08-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200801_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.Payment'),
        ),
    ]
