# Generated by Django 2.2 on 2020-08-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200801_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='order_id',
            field=models.CharField(default='1', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
