# Generated by Django 2.2 on 2020-09-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200928_2249'),
        ('cart', '0005_usercart_single_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PromoCode'),
        ),
    ]
